# Generated by Django 3.2.9 on 2021-11-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20211116_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='price',
            new_name='item_price',
        ),
    ]
