# Generated by Django 3.2.9 on 2021-11-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_printoptions_printoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='print',
            old_name='name',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='print',
            name='title',
            field=models.CharField(default='temp', max_length=254),
            preserve_default=False,
        ),
    ]
