# Generated by Django 3.2.9 on 2021-11-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_print_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='description',
        ),
    ]
