# Generated by Django 3.2.9 on 2021-11-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_print_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='printoption',
            name='orientation',
        ),
    ]
