# Generated by Django 3.2.9 on 2021-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211115_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printoption',
            name='dimensions',
            field=models.CharField(max_length=254),
        ),
    ]
