# Generated by Django 3.2.9 on 2021-11-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_printoption_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='artist',
        ),
    ]
