# Generated by Django 3.2.9 on 2021-11-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20211118_1819'),
        ('products', '0009_remove_print_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.artist'),
        ),
    ]
